development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:ca4dbda1021736e3a2a2f8ed073fae92@crestfish.redistogo.com:11285/
  channel_prefix: tense_production
